site_name: Jason's Cookbook

theme:
  name: material

nav:
  - Home: index.md
  - Japanese:
      - Gyudon: japanese/Gyudon.md
      - Miso Katsu: japanese/Miso-Katsu.md
  - Random:
      - Chicken Bake - Meal Prep Idea: random/Chicken Bake, Meal prep idea.md
      - Mexican Street Corn Chicken Orzo Bake: random/Mexican Street Corn Chicken Orzo Bake.md
      - One-Pot Taco Rice: random/One pot Taco-Rice.md
