site_name: Jason & Pearl's Cookbook!

theme:
  name: material

nav:
  - Home: index.md
  - Japanese:
      - Gyudon: Japanese/gyudon.md
      - Miso Katsu: Japanese/miso-katsu.md
  - Random:
      - Chicken Bake - Meal Prep Idea: Random/chicken-bake-meal-prep-idea.md
      - Mexican Street Corn Chicken Orzo Bake: Random/mexican-street-corn-chicken-orzo-bake.md
      - One-Pot Taco Rice: Random/one-pot-taco-rice.md
